kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: <STORAGECLASSNAME>
provisioner: efs.csi.aws.com
parameters:
  basePath: <PATH>
  directoryPerms: '755'
  fileSystemId: <FILESYSTEMID>
  gidRangeEnd: <gidRangeEnd>
  gidRangeStart: <gidRangeStart>
  provisioningMode: efs-ap
reclaimPolicy: Delete
volumeBindingMode: Immediate
